services:
  redpanda:
    image: redpandadata/redpanda:v24.1.3
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092,OUTSIDE://localhost:29092
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - REDPANDA_AUTO_CREATE_TOPICS_ENABLED=true

  redpanda-console:
    image: redpandadata/console:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=redpanda:9092
      - KAFKA_BROKER_AUTO_DISCOVERY=false
    depends_on:
      - redpanda